apps/categoria/urls.py
from django.conf.urls import url
from apps.categoria.api import CategoriaListAPIView,AnunciosAPIView
from apps.categoria.views import Categorias

    
urlpatterns = [
    url('categoriaAPI',CategoriaListAPIView.as_view(), name='ListaCategorias'),
    url(r'(?P<id>\d+)$',Categorias.as_view(), name='categorias'),
    url('AnunciosAPI', AnunciosAPIView.as_view(), name='anuncios')
]
    
    

apps/empresa/urls.py
from django.conf.urls import url
from apps.empresa.api import EmpresaListAPIView
from apps.empresa.views import Home


urlpatterns = [
    url('empresaAPI', EmpresaListAPIView.as_view(), name='empresaAPI'),
    url(r'^$', Home.as_view(), name='inicio'),
    
]

apps/producto/urls.py
from django.conf.urls import url
from apps.producto.api import ProductoDetalleListAPIView, ProductoListAPIView
from apps.producto.views import carrito, checkout, tienda,detalleProducto


urlpatterns = [
    url(r'^productoAPI$',ProductoListAPIView.as_view(), name='ListaProductos'),
    url(r'^detalle-productoAPI$',ProductoDetalleListAPIView.as_view(), name='detalleProductoAPI'),
    url(r'^tienda/(?P<id>\d+)$',tienda.as_view(), name='tienda'),
    url(r'^producto-detalle/(?P<id>\d+)$',detalleProducto.as_view(), name='detalleProducto'),
    url(r'^checkout/$',checkout.as_view(), name='checkout'),
    url(r'^carrito/$',carrito.as_view(), name='carrito'),
    
]

ecommerce/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/',include(('apps.empresa.urls','apps.empresa'),namespace='empresa')),
    url(r'^categoria/',include(('apps.categoria.urls','apps.categoria'),namespace='categoria')),
    url(r'^producto/',include(('apps.producto.urls','apps.producto'),namespace='producto')),
    url(r'^',include(('apps.empresa.urls','apps.empresa'),namespace='inicio'))
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/categoria/models.py
from email.mime import image
from statistics import mode
from django.db import models
from apps.empresa.models import Business

# Create your models here.
class Categoria (models.Model):
    business = models.ForeignKey(Business,verbose_name='Empresa', blank=False, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Categoría', max_length=50, blank=False)
    description = models.TextField(verbose_name='Descripción', blank=False)
    image = models.ImageField(verbose_name='Imagen', upload_to='categoria', blank=False)
    status = models.BooleanField(verbose_name='estado', help_text='Alta/Baja', default=True)

    def __str__(self):
        return '{}-{}'.format(self.name, self.business)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural ='Categorías'
        ordering = ('id',)

class Anuncio(models.Model):
    business = models.ForeignKey(Business,verbose_name='Empresa', blank=False, on_delete=models.CASCADE)
    evento = models.CharField(max_length=50, blank=True, null=True)
    image1 = models.ImageField(verbose_name='Imagen Principal', upload_to='anuncio')
    image2 = models.ImageField(verbose_name='Imagen Secundaria', upload_to='anuncio')

    def __str__(self):
        return self.evento

    class Meta:
        verbose_name ='Anuncio'
        verbose_name_plural = 'Anuncios'
        ordering = ('id',)

apps/empresa/models.py
from turtle import mode
from django.db import models

# Create your models here.

class Business(models.Model):
    name = models.CharField(verbose_name='Negocio', max_length=50, blank=False)
    direction = models.CharField(verbose_name='Dirección', max_length=50, blank=False)
    ruc = models.IntegerField(verbose_name='RUC', blank=True)
    history = models.TextField(verbose_name='Historia', blank=True)
    vision = models.TextField(verbose_name='visión', blank=False)
    mision = models.TextField(verbose_name='mision', blank=False)
    image = models.ImageField(verbose_name='imagen', upload_to='empresa', blank=False)
    status = models.BooleanField(verbose_name='Estado', help_text='Alta/Baja', default=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Negocio'
        verbose_name_plural = 'Negocios'

apps/producto/models.py
from turtle import mode
from unicodedata import name
from django.db import models
from apps.categoria.models import Categoria
from apps.empresa.models import Business

# Create your models here.

class Producto(models.Model):
    business = models.ForeignKey(Business,verbose_name='Empresa', blank=False, on_delete=models.CASCADE)
    category = models.ForeignKey(Categoria, verbose_name='Categoría', blank=False, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Nombre', max_length=50, blank=False)
    description = models.TextField(verbose_name='Descripción', blank=True)
    price = models.DecimalField(verbose_name='Precio', max_digits=5, decimal_places=2, blank=False)
    stock = models.IntegerField(verbose_name='Stock', blank=False)
    image1 = models.ImageField(verbose_name='Imagen 1', upload_to='producto', blank=False)
    image2 = models.ImageField(verbose_name='Imagen 2', upload_to='producto', blank=False)
    image3 = models.ImageField(verbose_name='Imagen 3', upload_to='producto', blank=False)
    image4 = models.ImageField(verbose_name='Imagen 4', upload_to='producto', blank=False)
    status = models.BooleanField(verbose_name='Estado', help_text='Alta/Baja', default=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural ='Productos'
        ordering = ('id',)

apps/categoria/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class Categorias(TemplateView):
    template_name = "categories.html"
    
    def get_context_data(self,**kwargs):
        if  kwargs.get('id'):
            self.request.session['idEmpresa']=kwargs.get('id')
        idEmpresa=self.request.session['idEmpresa']
        context = super().get_context_data()
        context["idEmpresa"] = idEmpresa
        #print (context["id"])
        return context

apps/empresa/views.py
from django.shortcuts import render
from django.template import Template
from django.views.generic import TemplateView
# Create your views here.

class Home (TemplateView):
    template_name = "index.html"

apps/producto/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.urls import reverse
# Create your views here.
class tienda (TemplateView):
    template_name ='products.html'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        if kwargs.get('id'):
            self.request.session['idCategoria']=kwargs.get('id')
        categoria = self.request.session['idCategoria']
        context["idEmpresa"] = self.request.session['idEmpresa']    
        context["idCategoria"] = categoria
        #print(context)
        return context
    

class detalleProducto(TemplateView):
    template_name='product-detail.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        #Obtiene id de Producto
        if kwargs.get('id'):
            self.request.session['idProducto']=kwargs.get('id')
        
        context["idProducto"]=self.request.session['idProducto']
        ##Obtener Url de Categorias
        idEmpresa = self.request.session["idEmpresa"]
        url = reverse('categoria:categorias', kwargs={'id': idEmpresa})
        context["urlCategoria"]=url

        ##Obtener Url de Tienda
        idCategoria = self.request.session["idCategoria"]
        urlTienda = reverse('producto:tienda', kwargs={'id':idCategoria})
        context["urlTienda"]=urlTienda
        ##print(context["idProducto"])
        return context

class checkout(TemplateView):
    template_name='checkout.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        idEmpresa = self.request.session["idEmpresa"]
        url = reverse('categoria:categorias', kwargs={'id': idEmpresa})
        context["urlCategoria"]=url
        print(url)
        return context


class carrito(TemplateView):
    template_name='carrito.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        if 'idEmpresa' in self.request.session:
            idEmpresa = self.request.session["idEmpresa"]
        else:
            idEmpresa = 1    
        url = reverse('categoria:categorias', kwargs={'id': idEmpresa})
        context["urlCategoria"]=url
        print(url)
        return context
    

templates/products.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Ecommerce | Tienda</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'base/img/core-img/favicon.ico'%}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static  'base/css/core-style.css'%}">
    <link rel="stylesheet" href="{% static 'custom/css/style.css'%}">

</head>

<body>
    <a href="https://wa.me/51950857035?text=Me%20gustaría%20contratar%20un%20servicio%20" class="whatsapp" target="_blank"> <i class="fa fa-whatsapp whatsapp-icon"></i></a>
    <div  class"icon-support" style="position:fixed;bottom:115px;right:2px;z-index:99;">
        <img width="120px"  src="http://127.0.0.1:8000/media/anuncio/support-icon.png">
    </div>
    <div id="loader" class="loader"></div>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="{% static 'base/img/core-img/search.png'%}" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="{%url 'inicio:inicio'%}"><img src="{% static 'base/img/core-img/logo_principal.png'%}" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix" style="padding-right:25px">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="{%url 'inicio:inicio'%}"><img src="{% static 'base/img/core-img/logo_principal.png'%}" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><a href="{%url 'inicio:inicio'%}">Inicio</a></li>
                   <!--<li><a href="about.html">Sobre Nosotros</a></li>-->
                    <!---
                    <li><a href="events.html">Eventos</a></li>
                    -->
                    <li class="active"><a href="">Tienda</a></li>
                   
                </ul>
            </nav>
           
            <!-- Button Group -->
             <!---
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            -->
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="{%url 'producto:carrito'%}" class="cart-nav"><img src="{% static 'base/img/core-img/cart.png'%}" alt=""> Carrito <span>(<span id="cantidad_items"></span>)</span></a>
                <a href="{%url 'producto:checkout'%}"class="fav-nav"><img src="{% static 'base/img/core-img/favorites.png'%}" alt=""> Checkout</a>
                <a href="#" class="search-nav"><img src="{% static 'base/img/core-img/search.png'%}" alt=""> Buscar</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
            <div id="anuncios" class="anuncios">
                
            </div>
        </header>
        <!-- Header Area End -->
<!--
        <div class="shop_sidebar_area">

           

                <h6 class="widget-title mb-30">Categorías</h6>

                
                
                <div class="catagories-menu">
                    <ul>
                        <li class="active"><a href="#">Ipsum</a></li>
                        <li><a href="#">Lorem Ipsum</a></li>
                        <li><a href="#">Ipsum</a></li>
                        <li><a href="#">Lorem</a></li>
                        <li><a href="#">Ipsum Lorem</a></li>
                        <li><a href="#">Lorem</a></li>
                        <li><a href="#">Ipsum</a></li>
                    </ul>
                </div>
            </div>



      

        
       
            <div class="widget price mb-50">
             
                <h6 class="widget-title mb-30">Precio</h6>

                <div class="widget-desc">
                    <div class="slider-range">
                        <div data-min="10" data-max="1000" data-unit="$" class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" data-value-min="10" data-value-max="1000" data-label-result="">
                            <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                        </div>
                        <div class="range-price">S/. 10 - S/. 1000</div>
                    </div>
                </div>
            </div>
        </div>
    -->
        <div class="amado_product_area section-padding-100">
            <div class="container-fluid">
                <div id="catalog-products" class="row">

                

                </div>


            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    <!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Suscríbete para un <span>25% de descuento</span></h2>
                        <p>Hola, llegaste aquí por algo. Regístrate y súmate a nuestros más de 500 suscriptores y obtén este descuento en tu próximo pedido. Recuerda que tu suscripción te permite acceder a otros beneficios como eventos y anuncios exclusivos.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Escribe tu correo">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="{% static 'base/img/core-img/logo_principal.png'%}"alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Todos los Derechos Reservados  | Empresa
</p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="index.html">Inicio</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="shop.html">Tienda</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="cart.html">Carrito</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="checkout.html">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
   
    <!-- ##### Footer Area End ##### -->

    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="{% static 'base/js/jquery/jquery-2.2.4.min.js'%}"></script>
    <!-- Popper js -->
    <script src="{% static 'base/js/popper.min.js'%}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'base/js/bootstrap.min.js'%}"></script>
    <!-- Plugins js -->
    <script src="{% static 'base/js/plugins.js'%}"></script>
    <!-- Active js -->
    <script src="{% static 'base/js/active.js'%}"></script>
    <!--Obtener Productos-->
    <script type="text/javascript">
        var UrlListProducto="{%url 'producto:ListaProductos'%}";
        var UrlAnuncios="{%url 'categoria:anuncios'%}";
        var idEmpresa = {{idEmpresa}};
        var idCategoria = {{idCategoria}};
        var carrito = JSON.parse(localStorage.getItem("carrito"));
        var canti;
        
        if (carrito===null){
            canti=0;
        }
        else{
            canti=carrito.length;
        }

        var $canti_items = $("#cantidad_items");
        localStorage.setItem("number_items",canti);
        $canti_items.html(canti);
    </script>
    <script src="{% static 'custom/js/products.js'%}"></script>

</body>

</html>